name: "🌍 New test provider request"
description: Submit a proposal for a new speedtest provider
title: "[New provider]: "
labels: [ "new-provider-request" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: checkboxes
    id: no_duplicate_issues
    attributes:
      label: "⚠️ Please verify that this feature request has NOT been raised before."
      description: Search in the issues sections by clicking [HERE](https://github.com/karelkryda/universal-speedtest/issues?q=new-provider-request)
      options:
        - label: I checked and didn't find similar feature request
          required: true
  - type: input
    id: url
    attributes:
      label: "🖇️ Test provider URL"
      description: Link to the test provider.
      placeholder: ex. speedtest.net
    validations:
      required: true
  - type: textarea
    id: explanation
    attributes:
      label: "❓ Why"
      description: A clear and concise description of why you would like to add this test provider.
      placeholder: ex. In my use-case, ...
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: "📝 Additional context"
      description: Add any other context or screenshots about the test provider request here.
      placeholder: ex. This test provider could...
    validations:
      required: false
