name: Release CD

on:
  release:
    types: [ released ]

jobs:
  publish:
    name: 📡 Production publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: 🛎️ Checkout code
        uses: actions/checkout@v4

      - name: 🔃 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - name: 🔧 Install dependencies
        run: npm install

      - name: 🏗️ Build library
        run: npm run build

      - name: 📡 Publish to NPM
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
